export class quickProductionSlip {
    "INSPECT"?:boolean;
    "INTERNAL_REFERENCE": number;
    "FICHENO": string;
    "DATE": string;
    "FTIME": number;
    "AUXIL_CODE": string;
    "AUTH_CODE": string;
    "ITEMREF": number;
    "ITEM_CODE": string;
    "UOMREF": number;
    "UEDIT": string;
    "USREF": number;
    "UUNIT": string;
    "UINFO1": number;
    "UINFO2": number;
    "UINFO3": number;
    "UINFO4": number;
    "UINFO5": number;
    "UINFO6": number;
    "UINFO7": number;
    "UINFO8": number;
    "ORDERREF": number;
    "ORDERFCNO": string;
    "AMOUNT": number;
    "DEPARTMENT": number;
    "SOURCEINDEX": number;
    "CAPIBLOCK_CREATEDBY": number;
    "CAPIBLOCK_CREADEDDATE": string;
    "CAPIBLOCK_CREATEDHOUR": number;
    "CAPIBLOCK_CREATEDMIN": number;
    "CAPIBLOCK_CREATEDSEC": number;
    "CAPIBLOCK_MODIFIEDBY": number;
    "CAPIBLOCK_MODIFIEDDATE": string;
    "CAPIBLOCK_MODIFIEDHOUR": number;
    "CAPIBLOCK_MODIFIEDMIN": number;
    "CAPIBLOCK_MODIFIEDSEC": number;
    "DATA_SITEID": number;
    "XML_ATTRIBUTE": number;
    "DATA_REFERENCE": number;
    "WFSTATUS": number;
    "PRODTYPE": number;
    "LOSTFACTOR": number;
    "PROJECTREF": number;
    "PROJECT_CODE": string;
    "DEF": string;
    "TRANSACTIONS": {
        "items": [
            {
                "LOGICALREF": number;
                "STCREF": number;
                "AMNT": number;
                "PRICE": number;
                "PERC": number;
                "MAINCREF": number;
                "LINENO": number;
                "LOSTFACTOR": number;
                "SOURCEINDEX": number;
                "UOMREF": number;
                "CARDTYPE": number;
                "SCODE": string;
                "SDEF": string;
                "UEDIT": string;
                "UUNIT": string;
                "CLIENTREF": number;
                "ARP_CODE": string;
                "COMP_TYPE": number;
                "ALT_ITEM_USE": number;
            }
        ]
    }
    "QPRODDELLINE": string;
    "CUROP": number;
    "FCNOCHANGED": number;
    "DOCNRREF": number;
    "STFCLIST": string;
    "DELOLDFC": number;
    "DELPROCTYP": number;
    "XBUFS": string;
    "APPROVE": number;
    "APPROVE_DATE": string;
    "CREATE_STFICHES": number;
    "CALC_OPTION": number;
    "CLIENTREF": number;
    "ARP_CODE": string;
    "CREATE_WH_FICHE": number;
    "NOTES1": string;
    "NOTES2": string;
    "NOTES3": string;
    "NOTES4": string
}