import { Component, OnInit } from '@angular/core';
import { MatDialogRef } from '@angular/material/dialog';
import { ToastrService } from 'ngx-toastr';
import { Subject } from 'rxjs';
import { invoiceTrans } from 'src/app/models/invoiceTrans';
import { paymentList } from 'src/app/models/paymentList';
import { salesInvoice } from 'src/app/models/salesInvoice';
import { salesOrder } from 'src/app/models/salesOrder';
import { SalesInvoicesService } from 'src/app/services/salesInvoices.service';

@Component({
  selector: 'app-dialog_newSalesInvoice',
  templateUrl: './dialog_newSalesInvoice.component.html',
  styleUrls: ['./dialog_newSalesInvoice.component.scss']
})
export class Dialog_newSalesInvoiceComponent implements OnInit {

  public newRecord: salesInvoice = new salesInvoice();
  public oTransLines = new Subject<invoiceTrans[]>();
  constructor(
    public dialogRef: MatDialogRef<Dialog_newSalesInvoiceComponent>,
    private toast: ToastrService,
    private svc: SalesInvoicesService
  ) {
    this.initializeRecord();
  }

  ngOnInit() {
    this.observeLines().subscribe(q => {
      this.newRecord.TRANSACTIONS.items = q
    })
  }

  create() {
    this.svc.add(this.newRecord).subscribe(res => {
      this.toast.success("Kayıt Başarılı", "", { positionClass: 'toast-top-center', timeOut: 3000 })
      this.dialogRef.close()
    }, err => {
      this.toast.error(err.error.ModelState.ValError0[0], "", { positionClass: 'toast-top-center', timeOut: 3000 })
      console.log(err)
    })
  }


  calculate() {
    let temp = {
      discount: 0,
      total: 0,
      vat: 0,
      totalNet: 0
    }
    this.newRecord.TRANSACTIONS.items.forEach(t => {
      t.TOTAL = t.QUANTITY * t.PRICE
      t.EXCHLINE_NET_DISC_AMOUNT = Math.round((t.TOTAL / 100) * t.DISCOUNT_RATE)
      t.VAT_AMOUNT = (t.QUANTITY * t.PRICE - t.EXCHLINE_NET_DISC_AMOUNT) * (t.VAT_RATE / 100)
      t.TOTAL_NET = t.TOTAL + t.VAT_AMOUNT

      console.log(t.EXCHLINE_NET_DISC_AMOUNT)

      temp.discount += t.EXCHLINE_NET_DISC_AMOUNT
      temp.total += t.TOTAL - t.EXCHLINE_NET_DISC_AMOUNT
      temp.vat += t.VAT_AMOUNT
      temp.totalNet += t.TOTAL_NET
    })

    this.newRecord.TOTAL_DISCOUNTS = parseInt(temp.discount.toFixed(2))
    this.newRecord.TOTAL_GROSS = parseInt(temp.total.toFixed(2))
    this.newRecord.TOTAL_VAT = parseInt(temp.vat.toFixed(2))
    this.newRecord.TOTAL_NET = parseInt(temp.totalNet.toFixed(2))
  }

  observeLines() {
    return this.oTransLines.asObservable();
  }


  newLine() {
    let line = new invoiceTrans();
    line.QUANTITY = 0;
    line.PRICE = 0;
    line.EXCHLINE_NET_DISC_AMOUNT = 0;
    line.TOTAL = 0;
    line.VAT_RATE = 18;
    line.TOTAL_NET = 0;
    line.DISCOUNT_RATE = 0;
    line.UNIT_CODE = "ADET"

    let temp = this.newRecord.TRANSACTIONS.items
    temp.push(line)
    this.oTransLines.next(temp)
    console.log(this.newRecord.TRANSACTIONS.items)
  }

  initializeRecord() {
    this.newRecord = {
      "INSPECT": false,
      "INTERNAL_REFERENCE": 0,
      "GRPCODE": 0,
      "TYPE": 8,
      "NUMBER": "",
      "DOC_TRACK_NR": "",
      "DATE": "",
      "TIME": 319627872,
      "DOC_NUMBER": "",
      "AUXIL_CODE": "",
      "AUTH_CODE": "",
      "ARP_CODE": "",
      "CLIENTREF": 5,
      "ARP_CODE_SHPM": "",
      "RECVREF": 0,
      "SHIPLOC_CODE": "",
      "OHP_CODE": "",
      "CENTERREF": 0,
      "GL_CODE": "",
      "ACCOUNTREF": 0,
      "SOURCE_WH": 0,
      "SOURCE_COST_GRP": 0,
      "CANCELLED": 0,
      "CANCEL_DATE": "1899-12-30T00:00:00",
      "GL_POSTED": 0,
      "PAIDINCASH": 0,
      "FROMSAFE": 0,
      "POST_FLAGS": 247,
      "VAT_RATE": 18.0,
      "ADD_DISCOUNTS": 0.0,
      "TOTAL_DISCOUNTS": 0.0,
      "TOTAL_DISCOUNTED": 0.0,
      "ADD_EXPENSES": 0.0,
      "TOTAL_EXPENSES": 0.0,
      "EXPENSE_DISTRB": 0.0,
      "TOTAL_DEPOSITED": 0.0,
      "TOTAL_PROMOTIONS": 0.0,
      "TOTAL_GROSSVINC": 0.0,
      "TOTAL_VAT": 0.0,
      "TOTAL_GROSS": 0.0,
      "TOTAL_NET": 0.0,
      "NOTES1": "",
      "NOTES2": "",
      "NOTES3": "",
      "NOTES4": "",
      "NOTES5": "",
      "NOTES6": "",
      "INTEREST_ACCRD": 0.0,
      "CURR_INVOICE": 0,
      "TC_XRATE": 0.0,
      "TC_NET": 0.0,
      "RC_XRATE": 0.0,
      "RC_NET": 0.0,
      "SINGLE_PAYMENT": 0,
      "KASTRANSREF": 0,
      "PAYMENT_CODE": "",
      "PAYDEFREF": 0,
      "PRINT_COUNTER": 0,
      "PRINT_DATE": "1899-12-30T00:00:00",
      "VAT_INCLUDED_GRS": 0,
      "DIVISION": 0,
      "DEPARTMENT": 0,
      "ACCFICHEREF": 0,
      "ADDEXPACCREF": 0,
      "ADDEXPCENTREF": 0,
      "PRICE_UPD_NEG": 0,
      "CREATED_BY": 1,
      "DATE_CREATED": "",
      "HOUR_CREATED": 0,
      "MIN_CREATED": 0,
      "SEC_CREATED": 0,
      "MODIFIED_BY": 0,
      "DATE_MODIFIED": "",
      "HOUR_MODIFIED": 0,
      "MIN_MODIFIED": 0,
      "SEC_MODIFIED": 0,
      "SALESMAN_CODE": "",
      "SALESMANREF": 0,
      "CANCELLEDACC": 0,
      "SHIPMENT_TYPE": "",
      "SHIPPING_AGENT": "",
      "TRACK_NR": "",
      "CURRSEL_TOTALS": 1,
      "CURRSEL_DETAILS": 0,
      "TRADING_GRP": "",
      "TEXTINC": 0,
      "DATA_SITEID": 0,
      "DATA_REFERENCE": 1,
      "FACTORY": 0,
      "DISPATCH_DATE": 0,
      "DISP_NUMBER": "",
      "DISPATCHES": {
        "items": []
      },
      "TRANSACTIONS": {
        "items": [
          {
            "INTERNAL_REFERENCE": 0,
            "TYPE": 0,
            "MASTER_CODE": "",
            "STOCKREF": 0,
            "PREVLINEREF": 0,
            "PREVLINENO": 0,
            "DETLINE": 0,
            "TRCODE": 1,
            "DATE": "",
            "FTIME": 0,
            "DETAIL_LEVEL": 0,
            "DISCEXP_CALC": 0,
            "PRODORDERREF": 0,
            "PORDER_TYPE": 0,
            "QPROD_TYPE": 0,
            "QPROD_ITEM_TYPE": 0,
            "SUBCONTORDERREF": 0,
            "SCORDER_NUMBER": "",
            "SOURCETYPE": 0,
            "SOURCEINDEX": 0,
            "SOURCECOSTGRP": 0,
            "SOURCEWSREF": 0,
            "SOURCEPOLNREF": 0,
            "DESTTYPE": 0,
            "DESTINDEX": 0,
            "DESTCOSTGRP": 0,
            "DESTWSREF": 0,
            "DESTPOLNREF": 0,
            "FACTORYNR": 0,
            "IOCODE": 1,
            "STFICHEREF": 0,
            "STFICHELNNO": 0,
            "INVOICEREF": 0,
            "INVOICELNNO": 0,
            "CLIENTREF": 0,
            "ORDER_REFERENCE": 0,
            "ORDER_NUMBER": "",
            "ORDER_SITE": 0,
            "OFFERTRANS_REF": 0,
            "OFFERTRANS_SITE": 0,
            "OHP_CODE1": "",
            "CENTERREF": 0,
            "GL_CODE1": "",
            "ACCOUNTREF": 0,
            "GL_CODE2": "",
            "VATACCREF": 0,
            "OHP_CODE2": "",
            "VATCENTERREF": 0,
            "GL_CODE3": "",
            "PRACCREF": 0,
            "OHP_CODE3": "",
            "PRCENTERREF": 0,
            "GL_CODE4": "",
            "PRVATACCREF": 0,
            "OHP_CODE4": "",
            "PRVATCENREF": 0,
            "PROMOTION_CODE": "",
            "PROMREF": 0,
            "ADDITIONAL_ITEMS_CODE": "",
            "PAYMENT_CODE": "",
            "PAYDEFREF": 0,
            "AUXIL_CODE": "",
            "DELVRY_CODE": "",
            "MERGED_COUNT": 0,
            "QUANTITY": 0,
            "PRICE": 0,
            "TOTAL": 0,
            "CURR_PRICE": 0,
            "PC_PRICE": 0.0,
            "CURR_TRANSACTION": 0,
            "TC_XRATE": 0.0,
            "RC_XRATE": 0.0,
            "COST_DISTR": 0.0,
            "DISCOUNT_DISTR": 0.0,
            "EXPENSE_DISTR": 0.0,
            "PROMOTION_DISTR": 0.0,
            "DISCOUNT_RATE": 0.0,
            "BASE_AMOUNT": 0.0,
            "DESCRIPTION": "",
            "UNIT_CODE": "ADET",
            "UOMREF": 0,
            "USREF": 0,
            "UNIT_CONV1": 1.0,
            "UNIT_CONV2": 1.0,
            "UNIT_CONV3": 0.0,
            "UNIT_CONV4": 0.0,
            "UNIT_CONV5": 0.0,
            "UNIT_CONV6": 0.0,
            "UNIT_CONV7": 0.0,
            "UNIT_CONV8": 0.0,
            "UNIT_CONV9": 0.0,
            "VAT_INCLUDED": 0,
            "VAT_RATE": 18.0,
            "VAT_AMOUNT": 0.0,
            "VAT_BASE": 0,
            "VAT_ADJUSTMENT": 0.0,
            "BILLED_ITEM": 0,
            "BILLED": 0,
            "COMPOSITE": 0,
            "RET_COST_TYPE": 0,
            "SOURCE_SITE": 0,
            "SOURCE_REFERENCE": 0,
            "RET_COST": 0.0,
            "TC_RETCOST": 0.0,
            "OUT_COST": 0.0,
            "TC_OUTCOST": 0.0,
            "RET_QUANTITY": 0.0,
            "FIXAST_CODE": "",
            "FAREGREF": 0,
            "FIXAST_STATUS": 0,
            "CANCELLED": 0,
            "TOTAL_NET": 0,
            "DISTADDEXP": 0.0,
            "FADACCREF": 0,
            "FADCENTERREF": 0,
            "FARACCREF": 0,
            "FARCENTERREF": 0,
            "PRICE_UPDATE": 0.0,
            "PRICE_UPDCOST": 0.0,
            "PRICE_UPDNEG": 0,
            "LPRODSTAT": 0,
            "PROD_EXPN_DISTR": 0.0,
            "RC_PRICE_UPD": 0.0,
            "RC_PRICE_UPDCOST": 0.0,
            "SALESMANREF": 0,
            "FAPLACCREF": 0,
            "FAPLCENTERREF": 0,
            "OUTPUT_CODE": "",
            "DREF": 0,
            "COST_RATE": 0.0,
            "XPRICEUPD": 0,
            "XPRICE": 0.0,
            "XREPRATE": 0.0,
            "DISTCOEF": 0.0,
            "QC_OK": 0,
            "DATA_SITEID": 0,
            "DATA_REFERENCE": 4,
            "NET_DSC_FLAG": 0,
            "NET_DSC_RATE": 0.0,
            "NET_DSC_AMOUNT": 0.0,
            "DISPATCH_NUMBER": "",
            "SLDELLIST": "",
            "DETDELLIST": "",
            "XML_ATTRIBUTE": 2,
            "DIST_ORD_SITEIID": 0,
            "DIST_ORD_REFERENCE": 0,
            "CAMPAIGN_INFOS": {
              "items": [
                {
                  "CAMPCODE1": "",
                  "CAMPCODE2": "",
                  "CAMPCODE3": "",
                  "CAMPCODE4": "",
                  "CAMPCODE5": "",
                  "PCAMPCODE": "",
                  "CAMP_LN_NO": 0
                }
              ]
            },
            "CAMPAIGN_POINT": 0.0,
            "PROM_CLAS_ITEM_CODE": "",
            "VEND_COMM": 0.0,
            "PREV_OUT_COST": 0.0,
            "COSTOFSALEACCREF": 0,
            "COST_OF_SALE_GL_CODE": "",
            "PURCHACCREF": 0,
            "PURCH_GL_CODE": "",
            "COSTOFSALECNTREF": 0,
            "COST_OF_SALE_OHP_CODE": "",
            "PURCHCENTREF": 0,
            "PURCH_OHP_CODE": "",
            "PREV_OUT_COST_CURR": 0.0,
            "EU_VAT_AMOUNT": 0.0,
            "EU_VAT_STATUS": 0,
            "PR_RATE": 0.0,
            "ADD_TAX_RATE": 0.0,
            "ADD_TAX_CONV_FACT": 0.0,
            "ADD_TAX_AMOUNT": 0.0,
            "ADD_TAX_PRCOST": 0.0,
            "ADD_TAX_RETCOST": 0.0,
            "ADD_TAX_RETCOSTCURR": 0.0,
            "MULTI_ADD_TAX": 0,
            "GROSS_U_INFO1": 0.0,
            "GROSS_U_INFO2": 0.0,
            "ADD_TAX_PRCOSTCURR": 0.0,
            "ADD_TAX_ACCREF": 0,
            "GL_CODE5": "",
            "ADD_TAX_CENTERREF": 0,
            "OHP_CODE5": "",
            "ADD_TAX_AMNT_IS_UPD": 0,
            "PLN_STTRANS_PER_NR": 0,
            "PORD_CLS_PLN_AMNT": 0.0,
            "PLN_STTRANS_REFERENCE": 0,
            "PLN_AMOUNT": 0.0,
            "INFLATION_IDX": 0.0,
            "EDT_CURR": 1,
            "EDT_PRICE": 0.0,
            "PRDORD_TOT_COEF": 0.0,
            "DEMPEGGED_AMNT": 0.0,
            "STDUNIT_COST": 0.0,
            "STDRPUNIT_COST": 0.0,
            "INFLDX": 0.0,
            "COSTDIFF_ACCREF": 0,
            "COSTDIFF_ACCCODE": "",
            "COSTDIFF_CENREF": 0,
            "COSTDIFF_CENCODE": "",
            "ADDTAXDISC_AMNT": 0.0,
            "ORGLOGOID": "",
            "EXIM_FICHENO": "",
            "SALEMANCODE": "",
            "FACTORY": 0,
            "EXIM_FICHE_TYPE": 0,
            "TRANS_EXP_LINE": 0,
            "INS_EXP_LINE": 0,
            "EXIM_PROC_NO": 0,
            "EXIM_FILE_CODE": "",
            "EXIM_FILE_REF": 0,
            "EXIM_FILELINENR": 0,
            "EXIM_WHFICHE_NO": "",
            "EXIM_WHFICHE_REF": 0,
            "EXIM_WHFICHE_LNNO": 0,
            "ITEXT": "",
            "PROJECT_CODE": "",
            "PROJECTREF": 0,
            "DIIB_REF": 0,
            "DIIB_CODE": "",
            "MONTH": 0,
            "YEAR": 0,
            "PORDSYMOUTLN": 0,
            "PRCLISTREF": 0,
            "EXADDTAXRATE": 0.0,
            "EXADDTAXCONVF": 0.0,
            "EXADDTAXACODE": "",
            "EXADDTAXAREF": 0,
            "EXADDTAXCCODE": "",
            "EXADDTAXCREF": 0,
            "OTHRADDTAXACODE": "",
            "OTHRADDTAXAREF": 0,
            "OTHRADDTAXCCODE": "",
            "OTHRADDTAXCREF": 0,
            "EXADDTAXAMNT": 0.0,
            "AFFECT_COLLATRL": 0,
            "FROMORDWITHPAY": 0,
            "VARIANTREF": 0,
            "VARIANTCODE": "",
            "VARIANTNAME": "",
            "CANCONFIG": 0,
            "VCHARLIST": "0",
            "ADD_TAX_EFFECT_KDV": 0,
            "AFFECT_RISK": 0,
            "EXCHLINE_INTERNAL_REFERNCE": 0,
            "EXCHLINE_TRANS_REF": 0,
            "EXCHLINE_PRICE": 0.0,
            "EXCHLINE_TOTAL": 0.0,
            "EXCHLINE_DIST_COST": 0.0,
            "EXCHLINE_DIST_DISC": 0.0,
            "EXCHLINE_DIST_EXP": 0.0,
            "EXCHLINE_DIST_PROM": 0.0,
            "EXCHLINE_VAT_AMOUNT": 0.0,
            "EXCHLINE_VAT_MATRAH": 0.0,
            "EXCHLINE_LINE_NET": 0.0,
            "EXCHLINE_DIST_ADD_EXP": 0.0,
            "EXCHLINE_NET_DISC_AMOUNT": 0.0,
            "EXCHLINE_VAT_CALC_DIFF": 0.0,
            "EXCHLINE_EU_VAT_AMOUNT": 0.0,
            "EXCHLINE_ADD_TAX_AMOUNT": 0.0,
            "EXCHLINE_ADD_TAX_CONV_FACT": 0.0,
            "EXCHLINE_ADD_TAX_DISC_AMOUNT": 0.0,
            "EXCHLINE_EX_ADD_TAX_AMOUNT": 0.0,
            "EXCHLINE_EX_ADD_TAX_CONVF": 0.0,
            "ADD_TAX_VAT_MATRAH": 0.0,
            "EXCHLINE_ADD_TAX_VAT_MATRAH": 0.0,
            "ADD_TAX_REF": 0,
            "ADD_TAX_CODE": "",
            "ADDTAX_GLOBAL_CODE": "",
            "UNIT_GLOBAL_CODE": "",
            "PAYPL_GLOBAL_CODE": "",
            "PRCURR_GLOBAL_CODE": "",
            "TRCURR_GLOBAL_CODE": "",
            "EDTCURR_GLOBAL_CODE": "",
            "CANDEDUCT": 0,
            "MAIN_MT_REFERENCE": 0,
            "MAIN_MT_SITEID": 0,
            "PRCLISTCODE": "",
            "PRCLISTTYPE": 0,
            "FAPL_GL_CODE": "",
            "FAPL_OHP_CODE": "",
            "FAPROFITACCREF": 0,
            "FAPROFIT_GL_CODE": "",
            "FAPROFITCENTREF": 0,
            "FAPROFIT_OHP_CODE": "",
            "FALOSSACCREF": 0,
            "FALOSS_GL_CODE": "",
            "FALOSSCENTREF": 0,
            "FALOSS_OHP_CODE": "",
            "GLOBAL_ID": "",
            "DEDUCTION_PART1": 0,
            "DEDUCTION_PART2": 0,
            "GUID": "",
            "FAD_GL_CODE": "",
            "AUXIL_CODE2": "",
            "VATEXCEPT_REASON": "",
            "VATEXCEPT_CODE": "",
            "ADDTAXEXCEPT_REASON": "",
            "ADDTAXEXCEPT_CODE": "",
            "DEDUCTION_TOT": 0.0,
            "DEDUCTION_TOT_TC": 0.0,
            "MASTER_DEF": "",
            "MASTER_DEF2": "",
            "MASTER_DEF3": "",
            "BARCODE": "",
            "PARENTLNREF": 0,
            "DEDUCT_CODE": "",
            "DEDUCT_DEF": "",
            "FOREIGN_TRADE_TYPE": 0,
            "DISTRIBUTION_TYPE_WHS": 0,
            "DISTRIBUTION_TYPE_FNO": 0,
            "ITM_PROD_COUNTRY_CODE": "",
            "ITM_PROD_COUNTRY_DEF": "",
            "INF_DATE": "1899-12-30T00:00:00",
            "DEST_STATUS": 0,
            "REGTYPREF": 0,
            "REG_TYPE_CODE": "",
            "CPA_CODE": "",
            "GTIP_CODE": "",
            "PUBLICCOUNTRYREF": 0,
            "PUBLIC_COUNTRY_CODE": "",
            "PUBLIC_COUNTRY_NAME": "",
            "APPLY_ADD_TAX": 0,
            "FUTURE_MONTH_COUNT": 0,
            "FUTURE_MONTH_BEGDATE": "",
            "FUTURE_MONTH_ENDDATE": "",
            "QC_TRANSFER_REF": 0,
            "QC_TRANSFER_AMOUNT": 0.0,
            "FA_KKEG_AMOUNT": 0.0,
            "KKEGACCREF": 0,
            "KKEG_GL_CODE": "",
            "KKEGCENREF": 0,
            "KKEG_OHP_CODE": "",
            "KKEGVATACCREF": 0,
            "KKEG_VAT_GL_CODE": "",
            "KKEGVATCENREF": 0,
            "KKEG_VAT_OHP_CODE": "",
            "EXPRACCREF": 0,
            "EXPR_GL_CODE": "",
            "EXPRCNTRREF": 0,
            "EXPR_OHP_CODE": "",
            "MIDDLEMAN_EXP_TYPE": 0,
            "MARKING_TAGNO": "",
            "OWNER": "",
            "TCK_TAXNR": ""
          }
        ]
      },
      "PAYMENT_LIST": {
        "items": []
      },
      "DETLINES": "0",
      "STOPAJ_RATE": 0.0,
      "SSDF_RATE": 0.0,
      "BORSA_RATE": 0.0,
      "KOMISYON_RATE": 0.0,
      "KOMKDV_RATE": 0.0,
      "BAGKUR_RATE": 0.0,
      "STOPAJ": 0.0,
      "SSDF": 0.0,
      "BORSA": 0.0,
      "KOMISYON": 0.0,
      "KOMKDV": 0.0,
      "BAGKUR": 0.0,
      "EK1_PER": 0.0,
      "EK1": 0.0,
      "EK2_PER": 0.0,
      "EK2": 0.0,
      "STOPAJACC": "",
      "STOPAJACCREF": 0,
      "SSDFACC": "",
      "SSDFACCREF": 0,
      "BORSAACC": "",
      "BORSAACCREF": 0,
      "KOMISYONACC": "",
      "KOMISYONACCREF": 0,
      "KOMKDVACC": "",
      "KOMKDVACCREF": 0,
      "BAGKURACC": "",
      "BAGKURACCREF": 0,
      "STOPAJCOST": "",
      "STOPAJCREF": 0,
      "SSDFCOST": "",
      "SSDFCREF": 0,
      "BORSACOST": "",
      "BORSACREF": 0,
      "KOMISYONCOST": "",
      "KOMISYONCREF": 0,
      "KOMKDVCOST": "",
      "KOMKDVCREF": 0,
      "BAGKURCOST": "",
      "BAGKURCREF": 0,
      "KOM_TYPE": 0,
      "EK1ACC": "",
      "EK1ACCREF": 0,
      "EK2ACC": "",
      "EK2ACCREF": 0,
      "EK1COST": "",
      "EK1CREF": 0,
      "EK2COST": "",
      "EK2CREF": 0,
      "EK3ACC": "",
      "EK3ACCREF": 0,
      "EK4ACC": "",
      "EK4ACCREF": 0,
      "EK5ACC": "",
      "EK5ACCREF": 0,
      "EK3COST": "",
      "EK3CREF": 0,
      "EK4COST": "",
      "EK4CREF": 0,
      "EK5COST": "",
      "EK5CREF": 0,
      "STOPAJ_CALC_TYPE": 0,
      "BAGKUR_CALC_TYPE": 0,
      "XBUFS": "0",
      "DOCALS": "0",
      "ITEXT": "",
      "XML_ATTRIBUTE": 2,
      "DISTORDERREF": 0,
      "COSTOFSALEFCREF": 0,
      "DLV_CLIENT": 0,
      "OP_STATUS": 0,
      "TOTAL_ADD_TAX": 0.0,
      "PAYMENT_TYPE": 0,
      "ACCOUNTED_CNT": 0,
      "INFLATION_IDX": 0.0,
      "CASH_TRAN_GRP_NO": "",
      "CASH_TRAN_GRPLINE_NO": 0,
      "CASH_INFLDX": 0.0,
      "ORGLOGOID": "",
      "FROM_EXIM": 0,
      "CASH_ORGLOGOID": "",
      "FRG_TYP_CODE": "",
      "FRG_TYP_DESC": "",
      "EXIM_FICHE_TYPE": 0,
      "PROJECT_CODE": "",
      "PROJECTREF": 0,
      "WFLOWCARDREF": 0,
      "STATUS": 0,
      "DEDUCTIONPART1": 2,
      "DEDUCTIONPART2": 3,
      "DATA_LINK_REFERENCE": 1,
      "TOTALEXADDTAX": 0.0,
      "EXACCOUNTED": 0,
      "FROMBANK": 0,
      "BNTRANSREF": 0,
      "GUARANTOR1_FICHETYPE": 0,
      "GUARANTOR1_NR": 0,
      "GUARANTOR1_NAMESURNAME": "",
      "GUARANTOR1_ADDR1": "",
      "GUARANTOR1_ADDR2": "",
      "GUARANTOR1_DISTRICT": "",
      "GUARANTOR1_TOWN": "",
      "GUARANTOR1_CITY": "",
      "GUARANTOR1_COUNTRY": "",
      "GUARANTOR1_POSTCODE": "",
      "GUARANTOR1_TELNR1": "",
      "GUARANTOR1_TELNR2": "",
      "GUARANTOR1_FAXNR": "",
      "GUARANTOR1_SITEID": 0,
      "GUARANTOR1_ORGLOGICREF": 0,
      "GUARANTOR1_CLIENTREF": 0,
      "GUARANTOR1_TAXNR": "",
      "GUARANTOR1_TAXOFFICE": "",
      "GUARANTOR1_TAXXOFFCODE": "",
      "GUARANTOR1_BANKBRANCHCODE": "",
      "GUARANTOR1_BANKBRANCHS": "",
      "GUARANTOR1_BANKACCOUNTS": "",
      "GUARANTOR2_FICHETYPE": 0,
      "GUARANTOR2_NR": 0,
      "GUARANTOR2_NAMESURNAME": "",
      "GUARANTOR2_ADDR1": "",
      "GUARANTOR2_ADDR2": "",
      "GUARANTOR2_DISTRICT": "",
      "GUARANTOR2_TOWN": "",
      "GUARANTOR2_CITY": "",
      "GUARANTOR2_COUNTRY": "",
      "GUARANTOR2_POSTCODE": "",
      "GUARANTOR2_TELNR1": "",
      "GUARANTOR2_TELNR2": "",
      "GUARANTOR2_FAXNR": "",
      "GUARANTOR2_SITEID": 0,
      "GUARANTOR2_ORGLOGICREF": 0,
      "GUARANTOR2_CLIENTREF": 0,
      "GUARANTOR2_TAXNR": "",
      "GUARANTOR2_TAXOFFICE": "",
      "GUARANTOR2_TAXOFFCODE": "",
      "GUARANTOR2_BANKBRANCHCODE": "",
      "GUARANTOR2_BANKBRANCHS": "",
      "GUARANTOR2_BANKACCOUNTS": "",
      "AFFECT_COLLATRL": 0,
      "FROMORDWITHPAY": 0,
      "INTEL_LIST": {
        "items": [
          {
            "LOGICALREF": 0,
            "INVOICEREF": 0,
            "CLIENTREF": 0,
            "INVOICEINFO1": "",
            "INVOICEINFO2": "",
            "INVOICEINFO3": "",
            "INVOICEINFO4": "",
            "INVOICEINFO5": "",
            "INVOICEINFO6": "",
            "INVOICEINFO7": "",
            "INVOICEINFO8": "",
            "INVOICEINFO9": "",
            "INVOICEINFO10": "",
            "INTELDESC": "",
            "LINENUM": 0
          }
        ]
      },
      "GRPFIRMTRANS": 0,
      "AFFECT_RISK": 0,
      "EXCHINFO_INTERNAL_REFERENCE": 0,
      "EXCHINFO_FICHE_REF": 0,
      "EXCHINFO_ADD_DISCOUNTS": 0.0,
      "EXCHINFO_TOTAL_DISCOUNTS": 0.0,
      "EXCHINFO_TOTAL_DISCOUNTED": 0.0,
      "EXCHINFO_ADD_EXPENSES": 0.0,
      "EXCHINFO_TOTAL_EXPENSES": 0.0,
      "EXCHINFO_DIST_EXPENSE": 0.0,
      "EXCHINFO_TOTAL_DEPOZITO": 0.0,
      "EXCHINFO_TOTAL_PROMOTIONS": 0.0,
      "EXCHINFO_VAT_INC_GROSS": 0.0,
      "EXCHINFO_TOTAL_VAT": 0.0,
      "EXCHINFO_GROSS_TOTAL": 0.0,
      "EXCHINFO_TOTAL_ADD_TAX": 0.0,
      "EXCHINFO_TOTAL_EX_ADD_TAX": 0.0,
      "EXCHINFO_BAGKUR": 0.0,
      "EXCHINFO_STOPAJ": 0.0,
      "EXCHINFO_SSDF": 0.0,
      "EXCHINFO_BORSA": 0.0,
      "EXCHINFO_KOMISYON": 0.0,
      "EXCHINFO_KOM_KDV": 0.0,
      "EXCHINFO_EK1": 0.0,
      "EXCHINFO_EK2": 0.0,
      "EXCHINFO_EK3": 0.0,
      "EXCHINFO_EK4": 0.0,
      "EXCHINFO_EK5": 0.0,
      "CONTROL_INFO": 0,
      "POS_TRANSFER_INFO": 0,
      "TAX_FREE_CHECK": 0,
      "PASSPORT_NO": "",
      "CREDIT_CARD_NO": "",
      "CREDIT_CARD_NUMBER": "",
      "APPROVE": 0,
      "APPROVE_DATE": "1899-12-30T00:00:00",
      "ACC_FICHE_SITEID": 0,
      "ENTRUST": 0,
      "EK3_PER": 0.0,
      "EK3": 0.0,
      "EK4_PER": 0.0,
      "EK4": 0.0,
      "EK5_PER": 0.0,
      "EK5": 0.0,
      "DOC_DATE": "",
      "AUTOFILL_SLDETAILS": 0,
      "EINVOICE": 0,
      "PROFILE_ID": 0,
      "GUID": "",
      "ESEND_DATE": "1899-12-30T00:00:00",
      "ESTATUS": 12,
      "ESTARTDATE": "1899-12-30T00:00:00",
      "EENDDATE": "1899-12-30T00:00:00",
      "EDESCRIPTION": "",
      "EDURATION": 0.0,
      "EDURATION_TYPE": 0,
      "EINSTEAD_OF_DISPATCH": 0,
      "EINVOICE_SENDCUSTOM": 0,
      "EINVOICE_TAXTYPE": 0,
      "EINVOICE_TUNAME": "",
      "EINVOICE_TUSURNAME": "",
      "EINVOICE_TUPASSPORTNO": "",
      "EINVOICE_TUPASSPORTDATE": "1899-12-30T00:00:00",
      "EINVOICE_TUNATIONALITY": "",
      "EINVOICE_TUNATIONALITYNAME": "",
      "EINVOICE_TUBANKNAME": "",
      "EINVOICE_TUBNACCOUNTNO": "",
      "EINVOICE_TUBNBRANCH": "",
      "EINVOICE_TUPAYMENTNOTE": "",
      "EINVOICE_TUBNCURR": "",
      "EINVOICE_ADDR1": "",
      "EINVOICE_ADDR2": "",
      "EINVOICE_CITYCODE": "",
      "EINVOICE_CITY": "",
      "EINVOICE_COUNTRYCODE": "",
      "EINVOICE_COUNTRY": "",
      "EINVOICE_DISTRICTCODE": "",
      "EINVOICE_DISTRICT": "",
      "EINVOICE_TOWNCODE": "",
      "EINVOICE_TOWN": "",
      "EINVOICE_EXITTOWN": "",
      "EINVOICE_EXITGATECODE": "",
      "EINVOICE_EXITGATE": "",
      "EINVOICE_AGENCYCODE": "",
      "EINVOICE_AGENCY": "",
      "EINVOICE_EXITCOUNTRYCODE": "",
      "EINVOICE_EXITCOUNTRY": "",
      "EINVOICE_TRANSPORTTYP": 0,
      "EINVOICE_TRANSPORTTYPCODE": "",
      "EINVOICE_TRANSPORTTYPNAME": "",
      "EINVOICE_EXITDATE": "1899-12-30T00:00:00",
      "EINVOICE_EXITTIME": "00:00:00",
      "EINVOICE_FLIGHTNUMBER": "",
      "EINVOICE_GUIDE": "",
      "EINVOICE_TURETPRICE": 0.0,
      "EINVOICE_TURETPRICESTR": "Sıfır TL",
      "EINVOICE_SENDEINVCUSTOM": 0,
      "EINVOICE_EINVOICETYPSGK": 0,
      "EINVOICE_TAXPAYERCODE": "",
      "EINVOICE_TAXPAYERNAME": "",
      "EINVOICE_DOCUMENTNOSGK": "",
      "EINVOICE_DRIVERNAME1": "",
      "EINVOICE_DRIVERSURNAME1": "",
      "EINVOICE_DRIVERTCKNO1": "",
      "EINVOICE_PLATENUM1": "",
      "EINVOICE_CHASSISNUM1": "",
      "EINVOICE_DRIVERNAME2": "",
      "EINVOICE_DRIVERSURNAME2": "",
      "EINVOICE_DRIVERTCKNO2": "",
      "EINVOICE_PLATENUM2": "",
      "EINVOICE_CHASSISNUM2": "",
      "EINVOICE_DRIVERNAME3": "",
      "EINVOICE_DRIVERSURNAME3": "",
      "EINVOICE_DRIVERTCKNO3": "",
      "EINVOICE_PLATENUM3": "",
      "EINVOICE_CHASSISNUM3": "",
      "EINVOICE_CHAINDELIVERY": 0,
      "EINVOICE_SELLERCLIENTREF": 0,
      "EINVOICE_SELLERCLIENTCODE": "",
      "EINVOICE_TAXNRTOPAY": "",
      "PAYPLAN_GLOBAL_CODE": "",
      "TRCURR_GLOBAL_CODE": "",
      "EDTCURR_GLOBAL_CODE": "",
      "CANCEL_AUTO_GL_PROC": 0,
      "FILL_GL_CODES_CONN": 0,
      "FILL_GL_CODES_CARD": 0,
      "GLOBAL_ID": "",
      "DEVIR": 0,
      "LOC_CONTROL_OFF": 0,
      "CANT_CRE_DEDUCT": 0,
      "VATEXCEPT_REASON": "",
      "VATEXCEPT_CODE": "",
      "ADDTAXEXCEPT_REASON": "",
      "ADDTAXEXCEPT_CODE": "",
      "EINVOICE_TYPE": 0,
      "TOTAL_NET_STR": "",
      "TR_NET_STR": "",
      "CANCEL_AUTO_CAMP_PROC": 0,
      "CAMPAIGN_CODE": "",
      "SHIPLOC_DEF": "",
      "TOTAL_SERVICES": 0.0,
      "FROMEXCHDIFF": 0,
      "EXIMVAT": 0,
      "SERIAL_CODE": "",
      "CHECK_CLDAILYDEDUCTLIMIT": 0,
      "STAFF_OTHER_EXPENSES": 0,
      "OFFER_REFERENCE": 0,
      "NO_CALCULATE": 0,
      "APPLY_ARP_DISCOUNT": 0,
      "MARKREF": 0,
      "MARK_CODE": "",
      "EARCHIVEDETR_LOGICALREF": 0,
      "EARCHIVEDETR_INVOICEREF": 0,
      "EARCHIVEDETR_INSTALLMENTNUMBER": "",
      "EARCHIVEDETR_EARCHIVESTATUS": 0,
      "EARCHIVEDETR_EARCHIVESTATUSOLD": 0,
      "EARCHIVEDETR_SENDMOD": 0,
      "EARCHIVEDETR_INTSALESADDR": "",
      "EARCHIVEDETR_INTPAYMENTDESC": "",
      "EARCHIVEDETR_INTPAYMENTTYPE": 0,
      "EARCHIVEDETR_INTPAYMENTAGENT": "",
      "EARCHIVEDETR_INTPAYMENTDATEORG": 0,
      "EARCHIVEDETR_INTPAYMENTDATE": "",
      "EARCHIVEDETR_OCKSERIALNUMBER": "",
      "EARCHIVEDETR_OCKZNUMBER": "",
      "EARCHIVEDETR_OCKFICHENUMBER": "",
      "EARCHIVEDETR_OCKFICHEDATEORG": 0,
      "EARCHIVEDETR_OCKFICHEDATE": "",
      "EARCHIVEDETR_ISCOMP": 0,
      "EARCHIVEDETR_TAXNR": "",
      "EARCHIVEDETR_TCKNO": "",
      "EARCHIVEDETR_NAME": "",
      "EARCHIVEDETR_SURNAME": "",
      "EARCHIVEDETR_DEFINITION": "",
      "EARCHIVEDETR_ADDR1": "",
      "EARCHIVEDETR_ADDR2": "",
      "EARCHIVEDETR_CITYCODE": "",
      "EARCHIVEDETR_CITY": "",
      "EARCHIVEDETR_COUNTRYCODE": "",
      "EARCHIVEDETR_COUNTRY": "",
      "EARCHIVEDETR_POSTCODE": "",
      "EARCHIVEDETR_DISTRICTCODE": "",
      "EARCHIVEDETR_DISTRICT": "",
      "EARCHIVEDETR_TOWNCODE": "",
      "EARCHIVEDETR_TOWN": "",
      "EARCHIVEDETR_EMAILADDR": "",
      "EARCHIVEDETR_ISPERCURR": 0,
      "EARCHIVEDETR_INSTEADOFDESP": 0,
      "EARCHIVEDETR_TAXOFFICE": "",
      "EARCHIVEDETR_TELCODES1": "",
      "EARCHIVEDETR_TELCODES2": "",
      "EARCHIVEDETR_TELNRS1": "",
      "EARCHIVEDETR_TELNRS2": "",
      "EARCHIVEDETR_OLDEARCHIVESTATUS": 0,
      "EARCHIVEDETR_DRIVERNAME1": "",
      "EARCHIVEDETR_DRIVERSURNAME1": "",
      "EARCHIVEDETR_DRIVERTCKNO1": "",
      "EARCHIVEDETR_PLATENUM1": "",
      "EARCHIVEDETR_CHASSISNUM1": "",
      "EARCHIVEDETR_DRIVERNAME2": "",
      "EARCHIVEDETR_DRIVERSURNAME2": "",
      "EARCHIVEDETR_DRIVERTCKNO2": "",
      "EARCHIVEDETR_PLATENUM2": "",
      "EARCHIVEDETR_CHASSISNUM2": "",
      "EARCHIVEDETR_DRIVERNAME3": "",
      "EARCHIVEDETR_DRIVERSURNAME3": "",
      "EARCHIVEDETR_DRIVERTCKNO3": "",
      "EARCHIVEDETR_PLATENUM3": "",
      "EARCHIVEDETR_CHASSISNUM3": "",
      "EARCHIVEDETR_CHAINDELIVERY": 0,
      "EARCHIVEDETR_SELLERCLIENTREF": 0,
      "EARCHIVEDETR_SELLERCLIENTCODE": "",
      "EBOOK_DOCDATE": "1899-12-30T00:00:00",
      "EBOOK_NODOCUMENT": 0,
      "EBOOK_DOCNR": "",
      "EBOOK_DOCTYPE": 0,
      "EBOOK_EXPLAIN": "",
      "EBOOK_PAYTYPE": "",
      "EBOOK_NOPAY": 0,
      "EPRODUCER_STATUS": 0,
      "EPRODUCER_SENDMOD": 0,
      "EPRODUCER_TAXNR": "",
      "EPRODUCER_TCKNO": "",
      "EPRODUCER_NAME": "",
      "EPRODUCER_SURNAME": "",
      "EPRODUCER_DEFINITION": "",
      "EPRODUCER_ADDR1": "",
      "EPRODUCER_ADDR2": "",
      "EPRODUCER_CITYCODE": "",
      "EPRODUCER_CITY": "",
      "EPRODUCER_COUNTRYCODE": "",
      "EPRODUCER_COUNTRY": "",
      "EPRODUCER_POSTCODE": "",
      "EPRODUCER_DISTRICTCODE": "",
      "EPRODUCER_DISTRICT": "",
      "EPRODUCER_TOWNCODE": "",
      "EPRODUCER_TOWN": "",
      "EPRODUCER_EMAILADDR": "",
      "EPRODUCER_ISCOMP": 0,
      "EPRODUCER_DELIVERYDATEORG": 0,
      "EPRODUCER_DELIVERYDATE": "",
      "EPRODUCER_ISPERCURR": 0,
      "IS_OKC_FICHE": 0,
      "OKCINFO_LIST": {
        "items": [
          {
            "INTERNAL_REFERENCE": 0,
            "INVOICE_REFERENCE": 0,
            "STFICHE_REFERENCE": 0,
            "FICHE_TYPE": 0,
            "FICHE_NUMBER": "",
            "DATE": "1899-12-30T00:00:00",
            "TIME": "00:00:00",
            "SERIAL_NUMBER": "",
            "Z_NUMBER": "",
            "FIXED_VALUE": "",
            "LINE_NUMBER": 0
          }
        ]
      },
      "EXIM_PAYTYPEREF": 0,
      "EXIM_PAYTYPE_CODE": "",
      "EXIM_PAYTYPE_NAME": "",
      "EXIM_BRBANKREF": 0,
      "EXIM_BRBANK_CODE": "",
      "EXIM_BRBANK_NAME": "",
      "DELIVERY_CODE": "",
      "ACCEPT_EINV_PUBLIC": 0,
      "PUBLICBNACCREF": 0,
      "PUBLIC_BNACC_CODE": "",
      "PUBLIC_BNACC_IBAN": "",
      "PUBLIC_BNACC_CURRENCY": 0,
      "TYPE_CODE": "",
      "FUTURE_MONTH_YREXPINC": 0,
      "DOC_DETAIL": 0,
      "CALC_ADD_TAX_VAT_SEP": 0
    }

  }

}
