USE [TIGERDB]
GO

/****** Object:  Table [dbo].[MOB_MENU_ACCESS]    Script Date: 02.09.2021 17:53:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MOB_MENU_ACCESS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USERNR] [smallint] NOT NULL,
	[MODULENR] [smallint] NOT NULL,
	[ALLOWED] [smallint] NOT NULL,
 CONSTRAINT [PK_MOB_MENU_ACCESS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[MOB_MENU_ACCESS]  WITH CHECK ADD  CONSTRAINT [FK_MOB_MENU_ACCESS_L_CAPIUSER] FOREIGN KEY([USERNR])
REFERENCES [dbo].[L_CAPIUSER] ([NR])
GO

ALTER TABLE [dbo].[MOB_MENU_ACCESS] CHECK CONSTRAINT [FK_MOB_MENU_ACCESS_L_CAPIUSER]
GO

ALTER TABLE [dbo].[MOB_MENU_ACCESS]  WITH CHECK ADD  CONSTRAINT [FK_MOB_MENU_ACCESS_MOB_MENU_ACCESS_DEFS] FOREIGN KEY([MODULENR])
REFERENCES [dbo].[MOB_MENU_ACCESS_DEFS] ([NR])
GO

ALTER TABLE [dbo].[MOB_MENU_ACCESS] CHECK CONSTRAINT [FK_MOB_MENU_ACCESS_MOB_MENU_ACCESS_DEFS]
GO

