USE [TIGERDB]
GO

/****** Object:  Table [dbo].[MOB_MENU_ACCESS_DEFS]    Script Date: 02.09.2021 17:53:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MOB_MENU_ACCESS_DEFS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NR] [smallint] NOT NULL,
	[DEFINITION] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_MOB_MENU_ACCESS_DEFS] PRIMARY KEY CLUSTERED 
(
	[NR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

